### PR TITLE
Add test cases in various classes

### PR DESCRIPTION
**Pull request by shreelakshmijoshi**
#### Created classes:

1. [TestUtil](https://github.com/datakaveri/iudx-resource-server/commit/ce86dce5c0ce3fea73f502e5c7b904d9eedc4d69)
2. [TestJwtData](https://github.com/datakaveri/iudx-resource-server/commit/b18b35f43fe1a9829f31c1ad31e5b7b55929a050)
3. [ParamsValidatorTest](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/21da026643928865e0a338878e1c789af39992ff)
4. [TestAsyncQueryListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)
5. [TestRevokeClientQListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)
6. [TestUniqueAttribQListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)

#### Added test cases in class : 

1. [QTypeValidatorTest](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/36cb58acd7d44893d662e574763a86efdaaac415)
2. [DatabaseServiceTest](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/5e602bf2131b293e1498e43a01834110587be549)
3. [DataBrokerServiceImplTest](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/2ee5529d1e4427f30cb251a3743f002467c8643a)

#### Changed classes:

1. [Util](https://github.com/datakaveri/iudx-resource-server/commit/e038e070bb56f46d38ae9a2d30b3b5233c95c4f1)
7. [QTypeValidator](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/7047e1e1be2b82958385315575bbee3a2bf7a055)
8. [RevokeClientQListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)
9. [AsyncQueryListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)
10. [UniqueAttribQListener](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/16def08ec7f5b5bfded03e0d90b02b51371437da)
11. [JwtAuthServiceTest](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/1c04259f04c38f35fcce69cc0a3095906d60c4d3)

#### To do:

- [x] Add  vertxTestContext.completeNow(); in MeteringServiceTest to avoid connection timed out exception : [Link 1](https://jenkins.iudx.io/job/iudx%20RS%20(PR)%20pipeline/200/#showFailuresLink), [Link 2](https://github.com/datakaveri/iudx-resource-server/pull/283/commits/128557b5aa6b4c5b5b323628d9c5c6480e2fc533)

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
retest this please

**Comment by shreelakshmijoshi** [comment]
Hi @karun-singh! could you please retest this? It seems the build failed due to this : 

> Error when executing failure post condition:
> hudson.AbortException: Test failure. Stopping pipeline execution!
> 	at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:63)
> 	at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:50)

**Comment by karun-singh** [comment]
> Hi @karun-singh! could you please retest this? It seems the build failed due to this :
> 
> > Error when executing failure post condition:
> > hudson.AbortException: Test failure. Stopping pipeline execution!
> > at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:63)
> > at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:50)

The build has failed due to failure in the integration tests. you can see the report [here](https://jenkins.iudx.io/job/iudx%20RS%20(PR)%20pipeline/207/Integration_20Test_20Report/).

**Comment by karun-singh** [comment]
retest this please

**Comment by shreelakshmijoshi** [comment]
ohh okay

**Comment by karun-singh** [comment]
> The build has failed due to failure in the integration tests

Seems like there is some issue with bringing up all the verticles before the integration test is performed. Looking into it.

**Comment by shreelakshmijoshi** [comment]
@karun-singh, I shall create another pull request to check if the same problem persists.

**Comment by karun-singh** [comment]
retest this please

**Comment by shreelakshmijoshi** [comment]
@karun-singh , ohh okay.. I'll check that now

**Comment by shreelakshmijoshi** [comment]
> @shreelakshmijoshi the databroker verticle is failing
> 
> ```
> perfTest_1  | time=2022-07-21T08:10:17+0000 level="FATAL" loggerName=iudx.resource.server.deploy.DeployerDev message="Failed to deploy iudx.resource.server.databroker.DataBrokerVerticle cause:" source=rs sourceUrl=https://rs-test.iudx.io exception=" java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because the return value of "io.vertx.core.Future.cause()" is null|at iudx.resource.server.databroker.listeners.RevokeClientQListener.start(RevokeClientQListener.java:76) ~[classes/:?]|	at iudx.resource.server.databroker.DataBrokerVerticle.start(DataBrokerVerticle.java:187) ~[classes/:?]|	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106) ~[vertx-core-4.0.3.jar:4.0.3]|	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196) ~[vertx-core-4.0.3.jar:4.0.3]|	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96) ~[vertx-core-4.0.3.jar:4.0.3]|	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59) ~[vertx-core-4.0.3.jar:4.0.3]|	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:40) ~[vertx-core-4.0.3.jar:4.0.3]|	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]|	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]|	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.60.Final.jar:4.1.60.Final]|	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]|	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]|	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.60.Final.jar:4.1.60.Final]|	at java.lang.Thread.run(Thread.java:833) [?:?]|"
> ```

could you please recheck if the same error is repeated ?

**Comment by karun-singh** [comment]
> could you please recheck if the same error is repeated? and is there any place which I could check these errors ?

@shreelakshmijoshi I was running the server locally with the code from this PR to check for these errors. Seems to have been resolved though, it's able to deploy all verticles successfully. 
The integration tests are failing though. Can see the report [here](https://jenkins.iudx.io/job/iudx%20RS%20(PR)%20pipeline/213/Integration_20Test_20Report/).
Looking into it.

**Comment by shreelakshmijoshi** [comment]
oh, that's great! Thanks

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Pull request merged**
