### PR TITLE
Enhancement/elastic java client

### PR DESCRIPTION
**Pull request by kailash**

### CODE REVIEW

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Pull request merged**
