### PR TITLE
Fixed issue 110

### PR DESCRIPTION
**Pull request by gopal-mahajan**
for issue 110

### CODE REVIEW

**Comment by gopal-mahajan** [comment]
[Newman Summary Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724890/Newman.Summary.Report.pdf)
[Surefire Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724891/Surefire.Report.pdf)

Attached Newman Summary and Surefire Report.

**Comment by swaminathanvasanth** [comment]
Can

> [Newman Summary Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724890/Newman.Summary.Report.pdf)
> [Surefire Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724891/Surefire.Report.pdf)
> 
> Attached Newman Summary and Surefire Report.

**Comment by swaminathanvasanth** [comment]
> > [Newman Summary Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724890/Newman.Summary.Report.pdf)
> > [Surefire Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6724891/Surefire.Report.pdf)
> > Attached Newman Summary and Surefire Report.

@kailash Can you check the Newman assertions? The rest looks good.

**Comment by gopal-mahajan** [comment]
[Newman Summary Report.pdf](https://github.com/datakaveri/iudx-resource-server/files/6725938/Newman.Summary.Report.pdf)
Updated Newman report

**Review by kailash — APPROVED** [review]
Newman test failures are because of Latest Verticle (Redis), all others are working fine.
LGTM for merge.

**Pull request merged**
