### PR TITLE
Resolve issue while appending subscritptions when there is only 1 bin…

### PR DESCRIPTION
**Pull request by Kranthi-Guribilli**
…ding

### CODE REVIEW

**Review by pranavrd — APPROVED** [review]
LGTM

**Comment by pranavrd** [comment]
Ok to test

**Comment by Kranthi-Guribilli** [comment]
Updated the corresponding junit test for listQueueSubscribers

**Comment by Kranthi-Guribilli** [comment]
ok to test

**Comment by pranavrd** [comment]
retest this please

**Pull request merged**
