### PR TITLE
Add Configurable base paths

### PR DESCRIPTION
**Pull request by shreelakshmijoshi**
Configurable base path added as `commonConfig` in config-dev

```
 "commonConfig" : {
        "dxApiBasePath" : "/ngsi-ld/v1"
    },
```

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by abhi4578** [comment]
ok to test

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
retest this please

**Comment by abhi4578** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by abhi4578** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Review by kailash — APPROVED** [review]

**Pull request merged**
