### PR TITLE
corrections to rs config

### PR DESCRIPTION
**Pull request by abhi4578**
- meteringPoolSize - https://github.com/datakaveri/iudx-resource-server/blob/e6b07eb03f0dba90be74170c74d36b6c4724026d/src/main/java/iudx/resource/server/metering/MeteringVerticle.java#L41
- databaseIp in postgres verticle https://github.com/datakaveri/iudx-resource-server/blob/e6b07eb03f0dba90be74170c74d36b6c4724026d/src/main/java/iudx/resource/server/database/postgres/PostgresVerticle.java#L37

### CODE REVIEW

**Review by kailash — APPROVED** [review]
LGTM

**Comment by abhi4578** [comment]
As callback verticle is not used at all. Can that config be removed @kailash to avoid confusion

**Comment by kailash** [comment]
@Abhilash yes, we can remove Callback verticle from config

**Comment by abhi4578** [comment]
> @abhilash yes, we can remove Callback verticle from config

Done

**Comment by kailash** [comment]
retest this please

**Pull request merged**
