### PR TITLE
Add Rest-Assured integration tests for Spatial Search APIs in the Resource Server along with the Rest Assure config file.

### PR DESCRIPTION
**Pull request by Kranthi-Guribilli**

### CODE REVIEW

**Comment by pranavrd** [comment]
Ok to test

**Comment by pranavrd** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by pranavrd** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Review by pranavrd — APPROVED** [review]
LGTM

**Pull request merged**
