### PR TITLE
Metering Service Updated- Response-size added

### PR DESCRIPTION
**Pull request by gopal-mahajan**
Count query might fail because we are using an older version of immudb in jenkins that does not support the new format for count query.

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
@gopal-mahajan  please resolve test failures.

**Comment by karun-singh** [comment]
retest this please

**Comment by swaminathanvasanth** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
@gopal-mahajan please fix this PR for failure.

**Pull request merged**
