### PR TITLE
Make basepath of reset user password API configurable

### PR DESCRIPTION
**Pull request by shreelakshmijoshi**
config-dev contains
```
"commonConfig" : {
        "dxApiBasePath" : "/ngsi-ld/v1"
   },
```

### CODE REVIEW

**Comment by kailash** [comment]
ok to test

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by karun-singh** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Comment by kailash** [comment]
retest this please

**Pull request merged**
