### PR TITLE
non-root image for resource server + change docker-compose file for temp storage + make apiserver port configurable

### PR DESCRIPTION
**Pull request by hackcoderr**
@abhi270595 
* Reduced the size of the image in comparison to the previous image.
*  Created non-root image, having username ``rs-user`` with uid ``1001``.

test:
1. checked ``docker top <container-name>``  and  the ``uid`` of process is ``1001``
```sh
hackcoderr@master-node:~/iudx$ docker top iudx-resource-server_prod_1
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
1001                5424                5392                67                  17:17               ?                   00:00:27            java -Xmx4096m -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar --host 506f7a5912e7 -c configs/config.json

```
2.  After exec into 
     i> checked the user, using ``id`` command - it has uid ``1001``.
  ```
hackcoderr@master-node:~/iudx/iudx-resource-server$ docker exec  -it iudx-resource-server_prod_1 bash
rs-user@12e566682cf5:/usr/share/app$ id
uid=1001(rs-user) gid=0(root) groups=0(root)
```

ii) tried to remove fatjar - it's not be able to remove the jar.
```
rs-user@12e566682cf5:/usr/share/app$ ls
configs  docs  fatjar.jar
rs-user@12e566682cf5:/usr/share/app$ rm -f fatjar.jar 
rm: cannot remove 'fatjar.jar': Permission denied
```
     
Any changes are required, plz let me know.

### CODE REVIEW

**Comment by abhi4578** [comment]
ok to test

**Comment by abhi4578** [comment]
restest this please

**Comment by abhi4578** [comment]
retest this please.

**Review by karun-singh — APPROVED** [review]
LGTM

**Pull request merged**
